CREATE TABLE Car
(
	Id NUMBER PRIMARY KEY,
	Price NUMBER (6,2) NOT NULL,
	RegistrationNumber NUMBER NOT NULL UNIQUE,
	MakeId NUMBER NOT NULL,
	RentalId NUMBER NOT NULL,
	FOREIGN KEY(MakeId) REFERENCES Make(Id)
	FOREIGN KEY(RentalId) REFERENCES Rental(Id)
);
