CREATE TABLE Car
(
	Id NUMBER GENERATED ALWAYS AS IDENTITY,
	Price NUMBER (6,2) NOT NULL,
	RegistrationNumber NVARCHAR2(6) NOT NULL UNIQUE,
	MakeId NUMBER NOT NULL,
	RentalId NUMBER NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(MakeId) REFERENCES Make(Id),
	FOREIGN KEY(RentalId) REFERENCES Rental(Id)
);
