CREATE TABLE Customer
(
	Id NUMBER PRIMAL KEY,
	Name NVARCHAR2(255) NOT NULL,
	Surname NVARCHAR2(255) NOT NULL,
	DocumentId NVARCHAR2(255) NOT NULL UNIQUE,
	RentalId NUMBER NOT NULL ,
	FOREIGN KEY(RentalId) REFERENCES Rental(Id)
);
